(ns kafka-test-app.news-handles
  (:use
   [twitter.oauth]
   [twitter.callbacks]
   [twitter.callbacks.handlers]
   [twitter.api.restful]))

(def my-creds (make-oauth-creds (System/getenv "TWITTER_CONSUMER_API_KEY")
                                (System/getenv "TWITTER_CONSUMER_SECRET")
                                (System/getenv "TWITTER_ACCESS_TOKEN")
                                (System/getenv "TWITTER_TOKEN_SECRET")))

(defn get-user [screen-name]
  (users-show :oauth-creds my-creds :params {:screen-name screen-name}))

(def news-handles '(
  "mashable"
  "cnnbrk"
  "big_picture"
  "theonion"
  "time"
  "breakingnews"
  "bbcbreaking"
  "espn"
  "harvardbiz"
  "gizmodo"
  "techcrunch"
  "wired"
  "wsj"
  "smashingmag"
  "pitchforkmedia"
  "rollingstone"
  "whitehouse"
  "cnn"
  "tweetmeme"
  "peoplemag"
  "natgeosociety"
  "nytimes"
  "lifehacker"
  "foxnews"
  "waitwait"
  "newsweek"
  "huffingtonpost"
  "newscientist"
  "mental_floss"
  "theeconomist"
  "emarketer"
  "engadget"
  "cracked"
  "slate"
  "bbcclick"
  "fastcompany"
  "reuters"
  "incmagazine"
  "eonline"
  "rww"
  "gdgt"
  "instyle"
  "mckquarterly"
  "enews"
  "nprnews"
  "usatoday"
  "mtv"
  "freakonomics"
  "boingboing"
  "billboarddotcom"
  "empiremagazine"
  "todayshow"
  "good"
  "gawker"
  "msnbc_breaking"
  "cbsnews"
  "guardiantech"
  "usweekly"
  "life"
  "sciam"
  "pastemagazine"
  "drudge_report"
  "parisreview"
  "latimes"
  "telegraphnews"
  "abc7"
  "arstechnica"
  "cnnmoney"
  "nprpolitics"
  "nytimesphoto"
  "nybooks"
  "nielsenwire"
  "io9"
  "sciencechannel"
  "usabreakingnews"
  "vanityfairmag"
  "cw_network"
  "bbcworld"
  "abc"
  "themoment"
  "socialmedia2day"
  "slashdot"
  "washingtonpost"
  "tpmmedia"
  "msnbc"
  "wnycradiolab"
  "cnnlive"
  "davos"
  "planetmoney"
  "cnetnews"
  "politico"
  "tvnewser"
  "guardiannews"
  "yahoonews"
  "seedmag"
  "tvguide"
  "travlandleisure"
  "newyorkpost"
  "discovermag"
  "sciencenewsorg"))
